name: 4 ハンズオン環境の削除

on: workflow_dispatch

env:
  ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }} 
  SESSION_NAME: gh-oidc-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  delete-stacks:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ap-northeast-1

      - name: VPCスタックの削除
        run: |
          aws cloudformation delete-stack --stack-name VPC-deploy
      - name: VPCスタックの削除完了待機
        run: |
          aws cloudformation wait stack-deploy-complete --stack-name VPC-deploy

      - name: ECSスタックの削除
        run: |
          aws cloudformation delete-stack --stack-name ECS-deploy
      - name: ECSスタックの削除完了待機
        run: |
          aws cloudformation wait stack-deploy-complete --stack-name ECS-deploy

      - name: CodeDeployスタックの削除
        run: |
          aws cloudformation delete-stack --stack-name CodeDeploy-deploy
      - name: CodeDeployスタックの削除完了待機
        run: |
          aws cloudformation wait stack-deploy-complete --stack-name CodeDeploy-deploy